#ifndef VSL
#define VSL 16
#endif
#ifndef VDL
#define VDL 8
#endif
MODULE VECJAC
  USE, INTRINSIC :: ISO_C_BINDING
  IMPLICIT NONE

  INTERFACE
     INTEGER FUNCTION SALLOC2(M, N, A, LDA) BIND(C,NAME='salloc2_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_PTR
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N
       INTEGER, INTENT(OUT) :: LDA
       TYPE(C_PTR), INTENT(OUT) :: A
     END FUNCTION SALLOC2
  END INTERFACE

  INTERFACE
     INTEGER FUNCTION DALLOC2(M, N, A, LDA) BIND(C,NAME='dalloc2_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_PTR
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N
       INTEGER, INTENT(OUT) :: LDA
       TYPE(C_PTR), INTENT(OUT) :: A
     END FUNCTION DALLOC2
  END INTERFACE

  INTERFACE
     INTEGER FUNCTION CALLOC2(M, N, A, LDA, AR, LDAR, AI, LDAI) BIND(C,NAME='calloc2_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_PTR
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N
       INTEGER, INTENT(OUT) :: LDA, LDAR, LDAI
       TYPE(C_PTR), INTENT(OUT) :: A, AR, AI
     END FUNCTION CALLOC2
  END INTERFACE

  INTERFACE
     INTEGER FUNCTION ZALLOC2(M, N, A, LDA, AR, LDAR, AI, LDAI) BIND(C,NAME='zalloc2_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_PTR
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N
       INTEGER, INTENT(OUT) :: LDA, LDAR, LDAI
       TYPE(C_PTR), INTENT(OUT) :: A, AR, AI
     END FUNCTION ZALLOC2
  END INTERFACE

  INTERFACE
     SUBROUTINE CZFREE(A) BIND(C,NAME='czfree_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_PTR
       IMPLICIT NONE
       TYPE(C_PTR), INTENT(INOUT) :: A
     END SUBROUTINE CZFREE
  END INTERFACE

  INTERFACE
     DOUBLE PRECISION FUNCTION DDPSCL(M, X, Y, E, F) BIND(C,NAME='ddpscl_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M
       DOUBLE PRECISION, INTENT(IN) :: X(MAX(M,VDL)), Y(MAX(M,VDL)), E(2), F(2)
     END FUNCTION DDPSCL
  END INTERFACE

  INTERFACE
     DOUBLE COMPLEX FUNCTION ZDPSCL(M, XR, XI, YR, YI, E, F) BIND(C,NAME='zdpscl_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M
       DOUBLE PRECISION, INTENT(IN) :: XR(MAX(M,VDL)), XI(MAX(M,VDL)), YR(MAX(M,VDL)), YI(MAX(M,VDL)), E(2), F(2)
     END FUNCTION ZDPSCL
  END INTERFACE

  ! ASSUMES (MOD(N,VSL) .EQ. 0)
  INTERFACE
     INTEGER FUNCTION SBJAC2(N, A11, A22, A21, C, AT, L1, L2, P) BIND(C,NAME='sbjac2_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_INT
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N
       REAL, INTENT(IN) :: A11(MAX(N,VSL)), A22(MAX(N,VSL)), A21(MAX(N,VSL))
       REAL, INTENT(OUT) :: C(MAX(N,VSL)), AT(MAX(N,VSL)), L1(MAX(N,VSL)), L2(MAX(N,VSL))
       INTEGER(KIND=C_INT), INTENT(OUT) :: P(MAX(N,VSL)/VSL)
     END FUNCTION SBJAC2
  END INTERFACE

  ! ASSUMES (MOD(N,VDL) .EQ. 0)
  INTERFACE
     INTEGER FUNCTION DBJAC2(N, A11, A22, A21, C, AT, L1, L2, P) BIND(C,NAME='dbjac2_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_INT
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N
       DOUBLE PRECISION, INTENT(IN) :: A11(MAX(N,VDL)), A22(MAX(N,VDL)), A21(MAX(N,VDL))
       DOUBLE PRECISION, INTENT(OUT) :: C(MAX(N,VDL)), AT(MAX(N,VDL)), L1(MAX(N,VDL)), L2(MAX(N,VDL))
       INTEGER(KIND=C_INT), INTENT(OUT) :: P(MAX(N,VDL)/VDL)
     END FUNCTION DBJAC2
  END INTERFACE

  ! ASSUMES MOD(N,VSL) .EQ. 0
  INTERFACE
     INTEGER FUNCTION CBJAC2(N, A11, A22, A21R, A21I, C, CAT, SAT, L1, L2, P) BIND(C,NAME='cbjac2_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_INT
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N
       REAL, INTENT(IN) :: A11(MAX(N,VSL)), A22(MAX(N,VSL)), A21R(MAX(N,VSL)), A21I(MAX(N,VSL))
       REAL, INTENT(OUT) :: C(MAX(N,VSL)), CAT(MAX(N,VSL)), SAT(MAX(N,VSL)), L1(MAX(N,VSL)), L2(MAX(N,VSL))
       INTEGER(KIND=C_INT), INTENT(OUT) :: P(MAX(N,VSL)/VSL)
     END FUNCTION CBJAC2
  END INTERFACE

  ! ASSUMES MOD(N,VDL) .EQ. 0
  INTERFACE
     INTEGER FUNCTION ZBJAC2(N, A11, A22, A21R, A21I, C, CAT, SAT, L1, L2, P) BIND(C,NAME='zbjac2_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_INT
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N
       DOUBLE PRECISION, INTENT(IN) :: A11(MAX(N,VDL)), A22(MAX(N,VDL)), A21R(MAX(N,VDL)), A21I(MAX(N,VDL))
       DOUBLE PRECISION, INTENT(OUT) :: C(MAX(N,VDL)), CAT(MAX(N,VDL)), SAT(MAX(N,VDL)), L1(MAX(N,VDL)), L2(MAX(N,VDL))
       INTEGER(KIND=C_INT), INTENT(OUT) :: P(MAX(N,VDL)/VDL)
     END FUNCTION ZBJAC2
  END INTERFACE

  INTERFACE
     DOUBLE PRECISION FUNCTION DJROT(N, X, Y, C, AT) BIND(C,NAME='djrot_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N
       DOUBLE PRECISION, INTENT(IN) :: C, AT
       DOUBLE PRECISION, INTENT(INOUT) :: X(MAX(N,VDL)), Y(MAX(N,VDL))
     END FUNCTION DJROT
  END INTERFACE

  ! a faster rotation without the max-norm computation
  INTERFACE
     INTEGER FUNCTION DJROTF(N, X, Y, C, AT) BIND(C,NAME='djrotf_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N
       DOUBLE PRECISION, INTENT(IN) :: C, AT
       DOUBLE PRECISION, INTENT(INOUT) :: X(MAX(N,VDL)), Y(MAX(N,VDL))
     END FUNCTION DJROTF
  END INTERFACE

  INTERFACE
     DOUBLE PRECISION FUNCTION ZJROT(N, XR, XI, YR, YI, C, CAT, SAT) BIND(C,NAME='zjrot_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N
       DOUBLE PRECISION, INTENT(IN) :: C, CAT, SAT
       DOUBLE PRECISION, INTENT(INOUT) :: XR(MAX(N,VDL)), XI(MAX(N,VDL)), YR(MAX(N,VDL)), YI(MAX(N,VDL))
     END FUNCTION ZJROT
  END INTERFACE

  ! a faster rotation without the max-norm computation
  INTERFACE
     INTEGER FUNCTION ZJROTF(N, XR, XI, YR, YI, C, CAT, SAT) BIND(C,NAME='zjrotf_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N
       DOUBLE PRECISION, INTENT(IN) :: C, CAT, SAT
       DOUBLE PRECISION, INTENT(INOUT) :: XR(MAX(N,VDL)), XI(MAX(N,VDL)), YR(MAX(N,VDL)), YI(MAX(N,VDL))
     END FUNCTION ZJROTF
  END INTERFACE

  INTERFACE
     INTEGER FUNCTION DSWP(N, X, Y) BIND(C,NAME='dswp_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: N
       DOUBLE PRECISION, INTENT(INOUT) :: X(MAX(N,VDL)), Y(MAX(N,VDL))
     END FUNCTION DSWP
  END INTERFACE

  INTERFACE
     DOUBLE PRECISION FUNCTION DNORM2(M, X, E0, F0, E1, F1) BIND(C,NAME='dnrom2_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M
       DOUBLE PRECISION, INTENT(IN) :: X(MAX(M,0))
       DOUBLE PRECISION, INTENT(OUT) :: E0, F0, E1, F1
     END FUNCTION DNORM2
  END INTERFACE

#ifdef USE_SLEEF
  INTERFACE
     DOUBLE PRECISION FUNCTION DNORMF(M, X, E0, F0, E1, F1) BIND(C,NAME='dnormf_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M
       DOUBLE PRECISION, INTENT(IN) :: X(MAX(M,0))
       DOUBLE PRECISION, INTENT(OUT) :: E0, F0, E1, F1
     END FUNCTION DNORMF
  END INTERFACE

  INTERFACE
     DOUBLE PRECISION FUNCTION DNORME(M, X, E0, F0, E1, F1) BIND(C,NAME='dnorme_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M
       DOUBLE PRECISION, INTENT(IN) :: X(MAX(M,VDL))
       DOUBLE PRECISION, INTENT(OUT) :: E0, F0, E1, F1
     END FUNCTION DNORME
  END INTERFACE

  INTERFACE
     DOUBLE PRECISION FUNCTION DNORMS(M, X, E0, F0, E1, F1) BIND(C,NAME='dnorms_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M
       DOUBLE PRECISION, INTENT(IN) :: X(MAX(M,VDL))
       DOUBLE PRECISION, INTENT(OUT) :: E0, F0, E1, F1
     END FUNCTION DNORMS
  END INTERFACE
#endif

  INTERFACE
     DOUBLE PRECISION FUNCTION ZNORM2(M, ZR, ZI, E0, F0, E1, F1) BIND(C,NAME='znrom2_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M
       DOUBLE PRECISION, INTENT(IN) :: ZR(MAX(M,0)), ZI(MAX(M,0))
       DOUBLE PRECISION, INTENT(OUT) :: E0, F0, E1, F1
     END FUNCTION ZNORM2
  END INTERFACE

  INTERFACE
     DOUBLE PRECISION FUNCTION DNORMX(M, N, A, LDA) BIND(C,NAME='dnormx_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDA
       DOUBLE PRECISION, INTENT(IN) :: A(MAX(LDA,VDL),MAX(N,0))
     END FUNCTION DNORMX
  END INTERFACE

  INTERFACE
     DOUBLE PRECISION FUNCTION ZNORMX(M, N, AR, LDAR, AI, LDAI) BIND(C,NAME='znormx_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDAR, LDAI
       DOUBLE PRECISION, INTENT(IN) :: AR(MAX(LDAR,VDL),MAX(N,0)), AI(MAX(LDAI,VDL),MAX(N,0))
     END FUNCTION ZNORMX
  END INTERFACE

  INTERFACE
     INTEGER FUNCTION DSCALE(M, N, A, LDA, E) BIND(C,NAME='dscale_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDA, E
       DOUBLE PRECISION, INTENT(INOUT) :: A(MAX(LDA,VDL),MAX(N,0))
     END FUNCTION DSCALE
  END INTERFACE

  INTERFACE
     INTEGER FUNCTION ZSCALE(M, N, AR, LDAR, AI, LDAI, E) BIND(C,NAME='zscale_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDAR, LDAI, E
       DOUBLE PRECISION, INTENT(INOUT) :: AR(MAX(LDAR,VDL),MAX(N,0)), AI(MAX(LDAI,VDL),MAX(N,0))
     END FUNCTION ZSCALE
  END INTERFACE

  ! ASSUMES (MOD(N,2) .EQ. 0) .AND. (MOD(N/2,VDL) .EQ. 0)
  INTERFACE
     INTEGER FUNCTION DVJSVD(M, N, G, LDG, V, LDV, ES, FS, JS, STP, SWP, WORK, IWORK) BIND(C,NAME='dvjsvd_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_INT
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDG, LDV, JS(*)
       INTEGER(KIND=C_INT), INTENT(IN) :: STP, SWP
       DOUBLE PRECISION, INTENT(INOUT) :: G(MAX(LDG,VDL),MAX(N,0))
       DOUBLE PRECISION, INTENT(OUT) :: V(MAX(LDV,VDL),MAX(N,0))
       DOUBLE PRECISION, INTENT(OUT) :: ES, FS, WORK(4*MAX(N,0))
       INTEGER(KIND=C_INT), INTENT(OUT) :: IWORK(MAX(N,0)/VDL)
     END FUNCTION DVJSVD
  END INTERFACE

  ! ASSUMES (MOD(N,2) .EQ. 0) .AND. (MOD(N/2,VDL) .EQ. 0)
  INTERFACE
     INTEGER FUNCTION ZVJSVD(M,N, GR,LDGR,GI,LDGI, VR,LDVR,VI,LDVI, ES,FS, JS,STP,SWP, WORK,IWORK) BIND(C,NAME='zvjsvd_')
       USE, INTRINSIC :: ISO_C_BINDING, ONLY: C_INT
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDGR, LDGI, LDVR, LDVI, JS(*)
       INTEGER(KIND=C_INT), INTENT(IN) :: STP, SWP
       DOUBLE PRECISION, INTENT(INOUT) :: GR(MAX(LDGR,VDL),MAX(N,0)), GI(MAX(LDGI,VDL),MAX(N,0))
       DOUBLE PRECISION, INTENT(OUT) :: VR(MAX(LDVR,VDL),MAX(N,0)), VI(MAX(LDVI,VDL),MAX(N,0))
       DOUBLE PRECISION, INTENT(OUT) :: ES, FS, WORK(5*MAX(N,0))
       INTEGER(KIND=C_INT), INTENT(OUT) :: IWORK(MAX(N,0)/VDL)
     END FUNCTION ZVJSVD
  END INTERFACE

  INTERFACE
     INTEGER FUNCTION CMERGE(M, N, AR, LDAR, AI, LDAI, A, LDA) BIND(C,NAME='cmerge_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDAR, LDAI, LDA
       REAL, INTENT(IN) :: AR(MAX(LDAR,VSL),MAX(N,0)), AI(MAX(LDAI,VSL),MAX(N,0))
       COMPLEX, INTENT(OUT) :: A(MAX(LDA,VSL/2),MAX(N,0))
     END FUNCTION CMERGE
  END INTERFACE

  INTERFACE
     INTEGER FUNCTION ZMERGE(M, N, AR, LDAR, AI, LDAI, A, LDA) BIND(C,NAME='zmerge_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDAR, LDAI, LDA
       DOUBLE PRECISION, INTENT(IN) :: AR(MAX(LDAR,VDL),MAX(N,0)), AI(MAX(LDAI,VDL),MAX(N,0))
       DOUBLE COMPLEX, INTENT(OUT) :: A(MAX(LDA,VDL/2),MAX(N,0))
     END FUNCTION ZMERGE
  END INTERFACE

  INTERFACE
     INTEGER FUNCTION CSPLIT(M, N, A, LDA, AR, LDAR, AI, LDAI) BIND(C,NAME='csplit_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDA, LDAR, LDAI
       COMPLEX, INTENT(IN) :: A(MAX(LDA,VSL/2),MAX(N,0))
       REAL, INTENT(OUT) :: AR(MAX(LDAR,VSL),MAX(N,0)), AI(MAX(LDAI,VSL),MAX(N,0))
     END FUNCTION CSPLIT
  END INTERFACE

  INTERFACE
     INTEGER FUNCTION ZSPLIT(M, N, A, LDA, AR, LDAR, AI, LDAI) BIND(C,NAME='zsplit_')
       IMPLICIT NONE
       INTEGER, INTENT(IN) :: M, N, LDA, LDAR, LDAI
       DOUBLE COMPLEX, INTENT(IN) :: A(MAX(LDA,VDL/2),MAX(N,0))
       DOUBLE PRECISION, INTENT(OUT) :: AR(MAX(LDAR,VDL),MAX(N,0)), AI(MAX(LDAI,VDL),MAX(N,0))
     END FUNCTION ZSPLIT
  END INTERFACE

CONTAINS
END MODULE VECJAC
